# Generated by Django 4.2.6 on 2023-10-19 16:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('letra', ckeditor.fields.RichTextField()),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
    ]
